### ISSUE TITLE
Signal holder structure

### ISSUE THREAD

**Issue by brunomonteiro98** [AutoMecUA/AutoMec-AD#100]
We need to construct a (wooden maybe) structure to hold a phone to show the signals. 
Check with LAR if they already have something like this

**Comment by manuelgitgomes** [comment]
Professor Artur has a working structure, we shall meet with him to learn how to mount it.

**Comment by manuelgitgomes** [comment]
Send an email to professor Artur to schedule a meeting

**Comment by manuelgitgomes** [comment]
We already have the structure! Now we need to acquire two old monitors!
![MicrosoftTeams-image](https://user-images.githubusercontent.com/58152228/146249267-fed25bce-50be-4ee3-a2fe-8fb3d91772b7.png)

**Comment by miguelriemoliveira** [comment]
I think you could speak to Eng. Rui Heitor in LAR.

Perhaps he has some.

Regards,
Miguel
*  Miguel Riem de Oliveira                                             *
Diretor de curso Mestrado Eng. Automação Industrial
email:    ***@***.***    |    ***@***.***
zoom: https://videoconf-colibri.zoom.us/j/7155402102
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by manuelgitgomes** [comment]
Thank you professor!

**Comment by brunomonteiro98** [comment]
@manuelgitgomes  do we still need the "chaves sextavadas" ?

**Comment by brunomonteiro98** [comment]
I will bring the tools

**Comment by Ze6000** [comment]
The signal holder structure is amost ready. The only thingh that's missing is a splitter e cables to connects a single pc to both monitors
