### ISSUE TITLE
Work over sliding windows method

### ISSUE THREAD

**Issue by Almeida-a** [AutoMecUA/AutoMec-AD#104]
Sliding windows is a common method to detect lanes in the context of autonomous driving. It was previously used with no meaningful results due to inexperience to further analyze said method.

In this issue we will revive this approach and discuss its potential to solve or help our lane detection objectives. 
This is a continuation to issue #91, where we concluded that this is a viable option.

**Comment by Almeida-a** [comment]
The [code](https://github.com/AutoMecUA/AutoMec-AD/blob/new/sliding_windows/lane_detection/script/sliding_windows.py) is in branch `new/sliding_windows`, and its path is `lane_detection/scripts/sliding_windows.py`.

Next steps:
- Test the code's robustness (find more bugs or problems with it).
- Resolve the bug where **one of the road lines is not visible**.
- Automate the gazebo/script running process with roslaunch.

**Comment by Almeida-a** [comment]
For good practice, we can use [rospy logging](http://wiki.ros.org/rospy/Overview/Logging). Here for a tutorial [page](http://wiki.ros.org/rospy_tutorials/Tutorials/Logging) over it.

**Comment by andrefdre** [comment]
I created a new model witth the camera view from the top. I'm remaking the code.

**Comment by andrefdre** [comment]
I based the code in a github page and was able to start detecting lines. Right now its onlt able to detect 2 lines at a time.
One of the aproachs is to change the code to detect 3 lines instead of 2. Another aproach is to remove the middle parte of the image so the middle lane isn't detected until one of the side lanes stops being detected and then uses the midle lane too.

**Comment by andrefdre** [comment]
Added the part of the code that calculates the position from the center and the curvatures of the road.
Added also the detection of lines using the previous image information obtained from the histograms

**Comment by manuelgitgomes** [comment]
Due to the current state of ML Algorithms, this is not needed.
