### ISSUE TITLE
Alternatives for physical track

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#107]
Due to some issues, the available track currently held at FCV will be no more. Research and procurement of alternatives are necessary. @PedroMS3 has volunteered to procure plastic sheets (around 40m²) and bring more information.

**Comment by manuelgitgomes** [comment]
An email should also be sent by me to CMA and CMI.

**Comment by PedroMS3** [comment]
i found that the solution i was looking for was too expensive for our budget, and also reflected a lot of light, which might disturb the camera's ability to perceive the track. I searched at Bricomarché for a kind of plastic wrap, there were 3 sizes 4x4, 4x6 and 4x10, the last 2 were not available.

**Comment by manuelgitgomes** [comment]
Two options arose. One near Mercado Municipal de Ílhavo:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/58152228/147588410-91679fcc-3cdd-4ea0-9ad5-fb896c6fa869.png)
And one near Estádio Municipal de Aveiro:
![image](https://user-images.githubusercontent.com/58152228/147588475-5e99017b-1901-4061-b6e0-9495e4c4e6c6.png)

**Comment by manuelgitgomes** [comment]
The option inside EMA was closed. A  picture:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/58152228/151067267-71245f5e-f68e-468f-a8cb-4216e9199981.png)


To note: In a brighter environment there should be darker lines.
Closing issue,
