### ISSUE TITLE
USB Camera suport

### ISSUE THREAD

**Issue by brunomonteiro98** [AutoMecUA/AutoMec-AD#113]
Design and print a support for the usb camera to point up to the signals

**Comment by brunomonteiro98** [comment]
50mm base 10 mm height and extruded 50mm

**Comment by PedroMS3** [comment]
the support has been modelled on SW and is now waiting for being gcoded

**Comment by manuelgitgomes** [comment]
New usb cam arrived, there is a need to create a new support

**Comment by manuelgitgomes** [comment]
New usb cam arrived, there is a need to create a new support

**Comment by manuelgitgomes** [comment]
The latest support occludes the image the kinect sees. A new support is needed ASAP.

**Comment by manuelgitgomes** [comment]
Two cameras are needed, so a new support was designed

**Comment by manuelgitgomes** [comment]
Done.
