### ISSUE TITLE
Automec's 3D Printer 

### ISSUE THREAD

**Issue by brunomonteiro98** [AutoMecUA/AutoMec-AD#114]
We need to get the printer working. 
The relevant links are on the chat of Carro Geral

**Comment by HugoSachim** [comment]
We performed the firmware update but it has problems reading the g.code file

**Comment by BernardoQuiterio** [comment]
the printer already detects the g.code but dost not extrude, moves really slowly and tries to move against the limit

**Comment by manuelgitgomes** [comment]
Software to try: AXON

**Comment by manuelgitgomes** [comment]
Tried several methods to make this work, but nothing happened. Abandoning this for now.
