### ISSUE TITLE
Light sources and noise Gazebo

### ISSUE THREAD

**Issue by brunomonteiro98** [AutoMecUA/AutoMec-AD#118]
We need a way to add noise to our world in gazebo to better represente reality.

**Comment by brunomonteiro98** [comment]
We weren't able to produce enough "noise" (with adicional light sources) because the floor isn't refletive enough. Maybe Professor @miguelriemoliveira  might helps us with this.

**Comment by manuelgitgomes** [comment]
We should check the .gazebo file of our world to see the properties. In last case, an object with infinitely large are and infinitesimally small thickness should be placed between the car and the track. That object would have the reflecting properties

**Comment by manuelgitgomes** [comment]
This can be done on data augmentation of cnn, so is not needed.

**Comment by manuelgitgomes** [comment]
Possibly add random models to gazebo.
