### ISSUE TITLE
Autonomous Driving Reinforcement Learning 

### ISSUE THREAD

**Issue by Joaoprcf** [AutoMecUA/AutoMec-AD#124]
We need a reward system given by gazebo services.
The first Reinforcement learning technique applied will be ARS (Augmented Random Search), which will be improved with a 2-3 layer neural network after the initial training (step 2), this new structure will have its weights on the first layers and the last one can be retrained again with ARS. The inputs given to this model can be obtained through CNN preprocessing and others. A script with capabilities to spawn and delete models is required.

**Comment by manuelgitgomes** [comment]
Revise requirements.txt.

**Comment by manuelgitgomes** [comment]
ROTA implementation should also be studied @brnaguiar

**Comment by manuelgitgomes** [comment]
For the referee try researching for frenet coordinates:
https://www.selfdrivingcars360.com/glossary/frenet-coordinates/

**Comment by manuelgitgomes** [comment]
Search for transformers use in autonomous driving

**Comment by manuelgitgomes** [comment]
Study the code in:
https://github.com/AutoMecUA/AutoMec-AD/blob/fec62272809c74442c5ee7295ec3230bd90147ed/prometheus_driving/scripts/ml_training.ipynb

This is a CNN and we are trying to change it to an RNN.

**Comment by PedroMS3** [comment]
For the moment being there is no member capable of working on this issue, therefore if we could get any member  that knows reinforcement learning would be great
