### ISSUE TITLE
Car safety system

### ISSUE THREAD

**Issue by brunomonteiro98** [AutoMecUA/AutoMec-AD#126]
We need to test the equipment that is going to be used in the competition.

For now, because the rule are not out yet, we need more information.

artur@ua.pt and asousa@fe.up.pt are the contacts to talk about this

**Comment by manuelgitgomes** [comment]
Prof. Artur response:
Viva!

O fim do semestre foi intenso e só agora estou a ultimar as regras. Espero terminá-las hoje ou amanhã. Não haverá alterações significativas. Apenas a pista encolherá ligeiramente, passando a largura a ser de 1,40m entre meios das linhas delimitadoras. Ou seja, a largura navegável será de 1,45m.

Cumps,
Artur Pereira

**Comment by manuelgitgomes** [comment]
Designed box and sketched electrical scheme, need to send an email to prof. Artur for further enlightenment.

**Comment by manuelgitgomes** [comment]
Not needed, closing

**Comment by manuelgitgomes** [comment]
On the future, have a stopping system with a controller
