### ISSUE TITLE
Code benchmarking

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#131]
Code is running slow and needs optimization.
Find out where bottlenecks are.
Try time measurements and python profiling.

Edit: Use the branch junk/issue131 for work related with this issue

**Comment by manuelgitgomes** [comment]
Python pdb

**Comment by Almeida-a** [comment]
I have used the integrated python profiler from pycharm to carry out the following evaluation:
![image](https://user-images.githubusercontent.com/40659508/159767232-8aa33c43-0648-4d00-a713-27874a222dad.png)

We can conclude that the matchTemplate function comprises the biggest bottleneck within the standalone script.
A small optimization was carried out: some unneeded templates for the template matching operation were [removed from the list](https://github.com/AutoMecUA/AutoMec-AD/blob/f408547f509db8835c035929c0a477ac21ac1761/signal_recognition/scripts/signal_panel_recognition_standalone.py#L234-L236).

The resulting profiling operation was as follows:
![image](https://user-images.githubusercontent.com/40659508/159769413-322d3c0c-dcd5-4522-811b-5808e2a3fd8b.png)

Which indicates that the overall cpu time consumption was cut by half.

Further work:
* Evaluate the optimization with the original (ROS) script
* If the optimization was not sufficient, continue analyzing and optimizing the code (using the standalone version and profiler first)

**Comment by Almeida-a** [comment]
After the optimizations carried out in the latest commit, the code yielded the following profiling results:
![image](https://user-images.githubusercontent.com/40659508/159773347-56155d6b-6aae-40bb-890a-ebea2a461e7a.png)

Further work:
 * Same from my last comment
 * Calculate and compare the cycle time from the latest commit to the first one (the one that yielded the first profiling results, which is the code without optimizations)

**Comment by manuelgitgomes** [comment]
After testing the code it was found that the optimization, even after the profiling, was not good enough. 
After searching if the openCV function had the option to search with a smaller number of matches, I could not find anything.
A better search for a bottleneck should happen soon.

**Comment by Almeida-a** [comment]
We have tested running the full project using 2 other computers, and it seems that it is working better than on the original one. Thus, we are assuming the problem is not with the code itself, and therefore I think this issue can be closed.

**Comment by manuelgitgomes** [comment]
Further testing might be needed but we can close this for now.
