### ISSUE TITLE
CNN Datasets/Models Needed

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#135]
To bring to FNR we need:

- Real dataset and model;
- Gazebo dataset and model;
- Mixed model;

On FNR we will test these models, pick the best one and do transferred learning onto it.

**Comment by brnaguiar** [comment]
- [ ] Real dataset and model tested

**Comment by manuelgitgomes** [comment]
FNR passed, closing issue.
Translation between gazebo and real-life not proved due to inaccuracies in camera angle and velocity
