### ISSUE TITLE
Create a support to lift the car

### ISSUE THREAD

**Issue by Ze6000** [AutoMecUA/AutoMec-AD#138]
Until now we normally use two chairs to hold the car, that might be inconvinient, so we need to design something to hold it like a car jack.

**Comment by brunomonteiro98** [comment]
The rear and frontal support were design now we need to print it.  
https://uapt33090-my.sharepoint.com/:u:/g/personal/ped_mende_ua_pt/EcXBGfvt7XhGpn0lez_Xyl4BX7W_ACVQhu4zC-MyXrHoSQ

https://uapt33090-my.sharepoint.com/:u:/g/personal/ped_mende_ua_pt/EU_HQl7QBwtLqJNlOFWsVIYB3gJvYHLIWBxA9NoNJKHVdQ

**Comment by manuelgitgomes** [comment]
I can print this, this week

**Comment by manuelgitgomes** [comment]
@PedroMS3 send me the stl of the front piece

**Comment by PedroMS3** [comment]
stl sent

**Comment by manuelgitgomes** [comment]
Printed with defected, maintenance needed
