### ISSUE TITLE
Add encoder to motors

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#141]
To run the car at a fixed velocity, add an encoder

**Comment by manuelgitgomes** [comment]
Ino code used in atlascar2:
https://github.com/lardemua/atlascar2/blob/master/atlascar2_description/nodes/Atlascar2_encoder_v2/Atlascar2_encoder_v2.ino

Used encoder:
https://pt.farnell.com/hengstler/ri32-0-1000er-14kb/encoder-rotary/dp/615985

Example of a cheaper one:
https://www.amazon.es/Codificador-Rotatorio-Incremental-Fotoel%C3%A9ctrico-Aceleraci%C3%B3n/dp/B07R8VSMQH/ref=sr_1_8?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=BAGDS9UKTE1S&keywords=encoder+50ppr&qid=1653945205&sprefix=encoder+50ppr%2Caps%2C105&sr=8-8

**Comment by Ze6000** [comment]
Some encoders
https://www.amazon.es/-/pt/dp/B015GYY7XU/ref=sr_1_23?keywords=encoder+giratorio&qid=1655123660&sprefix=encoder%2Caps%2C126&sr=8-23
https://www.amazon.es/Codificador-Rotatorio-Incremental-Fotoel%C3%A9ctrico-Aceleraci%C3%B3n/dp/B07R8VSMQH/ref=sr_1_8?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=BAGDS9UKTE1S&keywords=encoder+50ppr&qid=1653945205&sprefix=encoder+50ppr%2Caps%2C105&sr=8-8
https://pt.farnell.com/broadcom-limited/heds-9100-a00/encoder-rotary-500cpr-2ch/dp/1654864
https://pt.farnell.com/broadcom-limited/aedb-9140-a13/encoder-3channel-500cpr-8mm/dp/1161087
https://pt.farnell.com/broadcom-limited/heds-5640-a06/encoder-rotary-500ppr-3ch/dp/1654889

**Comment by andrefdre** [comment]
After some research wasn't able to choose a better encoder than @Ze6000 suggested,https://www.amazon.es/-/pt/dp/B015GYY7XU/ref=sr_1_23?keywords=encoder+giratorio&qid=1655123660&sprefix=encoder%2Caps%2C126&sr=8-23.

**Comment by manuelgitgomes** [comment]
The encoder:
https://www.amazon.es/-/pt/dp/B015GYY7XU/ref=sr_1_23?keywords=encoder+giratorio&qid=1655123660&sprefix=encoder%2Caps%2C126&sr=8-23.
Has been delivered and work can start on it.

**Comment by andrefdre** [comment]
After some research 2 more encoder opportunity appeared that were more compact. There is one which uses magnets and a TTL one. 
The magnetic encoder wasn't showing good values when connected to arduino so we decided to use the TTL one which is also easier to implement in the car.
To add the encoder to the car we though in gluing one part to the rotor and the other to the motor.
We also thought in adding a 3d printed cover to protect the encoder from dust.
![34e3a974-e05d-4a4a-8eaf-f71f0204074c](https://user-images.githubusercontent.com/58526188/192845209-72fb684e-5609-47b0-b0e5-554b5b4e245b.jpg)
![cbb10c3c-020f-4696-b2e1-1996d58d11d1](https://user-images.githubusercontent.com/58526188/192845213-65e2d874-76f4-4e85-8044-5dafdc514dbe.jpg)
![cc955dfb-397f-4945-9ae3-6211d6558929](https://user-images.githubusercontent.com/58526188/192845216-33aeaf18-f731-4dfb-95e6-bc1d5404e049.jpg)

**Comment by andrefdre** [comment]
The magnetic encoder was added to the motor and it's counting correctly one full rotation. We glued the magnet to the shaft and the encoder was mounted with some thin wire that was soldered to the motor pins.
![WhatsApp Image 2022-10-26 at 17 41 01](https://user-images.githubusercontent.com/58526188/198085652-9deb736b-0030-41da-87fb-e45ae16a72fa.jpeg)
![WhatsApp Image 2022-10-26 at 17 41 01 (1)](https://user-images.githubusercontent.com/58526188/198085691-c6387a77-d8a1-4dd4-8780-ae3ef01103f2.jpeg)
![WhatsApp Image 2022-10-26 at 17 41 02 (1)](https://user-images.githubusercontent.com/58526188/198085722-ea1fcfae-d170-4750-bb18-ff3ed72878c8.jpeg)
We dont have the connector that plugs in to the encoder so we need to buy it. The width of the connector is 13mm.
![WhatsApp Image 2022-10-26 at 17 41 02](https://user-images.githubusercontent.com/58526188/198085836-5c895c81-71c6-43e7-b111-2deacb385d50.jpeg)

**Comment by andrefdre** [comment]
After some research the Servo library isn't compatible with interrupts. In a post someone suggested to use the PCA9685 which we already have, some research about i2c and interrupts needs to be done to see if one affects the other.
![WhatsApp Image 2022-10-26 at 17 52 36](https://user-images.githubusercontent.com/58526188/198087538-26a634e6-ddcc-4833-ab25-eb6d3a7736dc.jpeg)

**Comment by andrefdre** [comment]
Now that the new PCB was made we need to see how the wires of the encoder will connect to the PCB:
- Solder directly
- Some kind of connector

**Comment by manuelgitgomes** [comment]
Next step: Run both:
https://github.com/AutoMecUA/AutoMec-AD/blob/e1438c8d650cd70405ed8875258501debccdc72b/prometheus_bringup/src/encoder_magnetic.ino
https://github.com/AutoMecUA/AutoMec-AD/blob/e1438c8d650cd70405ed8875258501debccdc72b/prometheus_bringup/src/int_to_movement.ino
In the same ESP, in different cores.

**Comment by andrefdre** [comment]
https://embeddedcorner.com/2021/02/03/install-ros-on-your-esp-board-with-arduino-ide/
Connection with esp32 and pc done as seen above.

**Comment by manuelgitgomes** [comment]
Design new way to lock the encoder relative to the motor

**Comment by manuelgitgomes** [comment]
@PedroMaia21 should take the pcb home to help in code development

**Comment by andrefdre** [comment]
At the end of the last meeting, @Manuelgitgomes and I found out that using 2 cores with ESP gave an error using ROS serial. More research is needed to figure out how we could solve this problem.

**Comment by manuelgitgomes** [comment]
Maybe we can use this arduino library: https://github.com/sachin0x18/rosserial_esp32

**Comment by manuelgitgomes** [comment]
Without using 2 core functionality, we have achieve (briefly) a fully functional encoder/motor control system.

**Comment by manuelgitgomes** [comment]
Encoder fully functional
