### ISSUE TITLE
Create development guides

### ISSUE THREAD

**Issue by Almeida-a** [AutoMecUA/AutoMec-AD#149]
Since we want all newcomers to integrate quickly and easily, I propose creating some software development guides, for example on the signal recognition package.

I will further detail this proposal shortly, like short, medium, and long-term goals.

In the meanwhile, any ideas are welcome!

PS: The idea, for now, is to create _.md_ files, since it's closer to the code (we can open the guide in our IDE), and also, it can provide a good overview and big-picture view of the code as opposed to the in-code documentation (e.g.: the docs written below the function signatures, for example).

**Comment by Almeida-a** [comment]
We can take advantage of the generated docs (from the in-code docs as well as from the _.md_ files) and create a webpage using github pages.

**Comment by Almeida-a** [comment]
Proposal for objectives:
 * Create a CONTRIBUTING.md describing guidelines for developers who would like to contribute to the project(s), whether on or off the university team.
 * Complete any unfinished in-code documentation
 * Create _.md_ files describing the techniques used to solve any of the main subjects' problems
 * Generate a (perhaps github) website using all of the produced documentation

I will organize this list into a short/medium/long term goals one.

**Comment by PedroMS3** [comment]
some of the shores in this issue dont make sense anymore, but Completing any unfinished in-code documentation will be implemented in issue #201
