### ISSUE TITLE
Create fast fastening system for car board

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#153]
Create an intuitive and easy to use system for fixing the mdf board to the car.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/58152228/180870097-e505ea45-5ac3-4a81-a545-998edb4d5690.png)

**Comment by manuelgitgomes** [comment]
@andrefdre is search for threads "porca de inserção" to use in this part

**Comment by andrefdre** [comment]
After searching for 3D imbedded threads this was the best option:
https://www.amazon.es/-/pt/dp/B09NPYX4YH/ref=sr_1_3?crid=1Y715PH5CMWBS&keywords=tuerca+de+inserto+3d+m8&qid=1659384528&sprefix=porca+de+inser%C3%A7%C3%A3o+3d+m8%2Caps%2C82&sr=8-3

**Comment by PedroMS3** [comment]
im not sure about the design of the insert for the imbedded threads on the part i made i think the threads wont stay in place as soon we torque the bolts

**Comment by PedroMS3** [comment]
the design has been completed, just missing the printing fase
