### ISSUE TITLE
Change mask mode from RGB to HSV

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#158]
Due to its intuitiveness, a change from RGB to HSV on mask mode seems like a good idea.

**Comment by rospuye** [comment]
I had some trouble at the beginning trying to test the mask mode, but once I figured out how to use the USB camera node to do it, making the change from RGB to HSV was simple. I also pushed the log files with the limits for green and red to the repository to substitute the RGB ones and avoid future file reading issues.
