### ISSUE TITLE
Fix signal panel in gazebo

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#160]
Signal panel is not working in gazebo. Check file:
https://github.com/AutoMecUA/AutoMec-AD/blob/73fdffd515ede05705bf378fcc9758bd49823821/prometheus_gazebo/src/gazebo_signalling_panel_controller.cpp

**Comment by inaciose** [comment]
Fixed in commit [Signal display #160]
