### ISSUE TITLE
Improve controller control

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#164]
Modify the node:
https://github.com/AutoMecUA/AutoMec-AD/blob/be51e989ed91b1927adc12557b649fe5bc7fe238/prometheus_bringup/scripts/joy_teleop.py

to place the linear velocity on the RT/R2 trigger.

**Comment by brunofavs** [comment]
[Added logic to 

`](https://github.com/AutoMecUA/AutoMec-AD/blob/fec62272809c74442c5ee7295ec3230bd90147ed/prometheus_bringup/scripts/joy_teleop.py#L16-L20)


https://github.com/AutoMecUA/AutoMec-AD/blob/fec62272809c74442c5ee7295ec3230bd90147ed/prometheus_bringup/scripts/twist_cap.py#L15
