### ISSUE TITLE
Test and correct 3D model of car

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#170]
Test an assembly of every part of the car and check if any errors occur. If so, correct them.

**Comment by Lara-Duarte** [comment]
![Captura de ecrã 2023-01-09 210506](https://user-images.githubusercontent.com/116599747/211408273-0c845330-04f2-4a6b-b86d-257fc1a41d8d.png)

**Comment by PedroMS3** [comment]
we have to verify the spacing for the kinectic that is going to be on the underside of th car
