### ISSUE TITLE
Build a new PCB  box and 2 battery shields to put under the car's board

### ISSUE THREAD

**Issue by PedroMS3** [AutoMecUA/AutoMec-AD#175]
the necessity to  move the initial location of the batteries and PCB box to under the car's board was identified, it creates more space on top of the board

**Comment by PedroMS3** [comment]
![image](https://user-images.githubusercontent.com/94935535/214158154-b976541d-bf82-4c5a-beb1-e655bd8b8512.png)
this is a initial sketch of the body that is going inside the battery holder

**Comment by PedroMS3** [comment]
![image](https://user-images.githubusercontent.com/94935535/214158478-ea5e8f6c-6810-4e75-95ec-e6e34ba6aeb2.png)
this is the new battery holder (it's missing another one on the other side of the body)

**Comment by PedroMS3** [comment]
it was suggested to use the body holding the battery holders to also hold the PCB, might use some "C" profiles on the sides of the PCB

**Comment by PedroMS3** [comment]
New design that already includes a part to position the PCB
![image](https://user-images.githubusercontent.com/94935535/214644605-f0f275fe-8df4-452e-bf30-12c9922cb60b.png)
![image](https://user-images.githubusercontent.com/94935535/214644709-9cfbcb05-9094-42aa-a5f8-7724e86d1db3.png)
Just missing the confirmation of some measurements

**Comment by manuelgitgomes** [comment]
Nice job, looks great! We can take these measurements next week!

**Comment by manuelgitgomes** [comment]
The PCB has 3mm of thickness and 80mm of width

**Comment by PedroMS3** [comment]
can we rotate the PCB 90º??
It would be easier for the design of the hardware
![image](https://user-images.githubusercontent.com/94935535/217927940-5b29e159-9ee6-43ae-9794-5a66cfd3b872.png)

**Comment by andrefdre** [comment]
Yes, I think we can the only restriction would be the battery cable, but I think it has more than enough.

**Comment by PedroMS3** [comment]
I am going to prepare the files for printing and testing

**Comment by manuelgitgomes** [comment]
Create a new part for step-down

**Comment by PedroMS3** [comment]
![image](https://user-images.githubusercontent.com/94935535/223249417-03b55a5b-0b0d-4c00-99b2-3fbdaf5f2a96.png)

the part for the step-down is done, the stl is on the hardware chat on Teams

**Comment by PedroMS3** [comment]
![image](https://user-images.githubusercontent.com/94935535/224842997-4815e573-6fe8-49a2-91a7-ef07d3dbac59.png)
the technical drawing has been made, i wil try to take the machined part to the next meeting

**Comment by PedroMS3** [comment]
the machined part is ready, i just have to re-drill some holes on the printed part

![Imagem WhatsApp 2023-03-20 às 21 37 00](https://user-images.githubusercontent.com/94935535/226472081-a4207170-2ad6-4dea-9167-df30f29495ec.jpg)

**Comment by PedroMS3** [comment]
some changes need to be made in the fixtures of the PCB cad
And some manual changes need to be made in parts "asa" and "aeroplano" with the dremel
also the complete parts of "asa" can be printed

**Comment by PedroMS3** [comment]
the "aeroplano" part has been mounted in the car chassis. It's missing the two "asa" pieces
![Imagem WhatsApp 2023-04-12 às 17 35 20](https://user-images.githubusercontent.com/94935535/231523915-e20bd385-cea4-4bc4-be4f-12ef1ec9915a.jpg)

**Comment by manuelgitgomes** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/58152228/232608249-8ee8410d-81a6-4dd4-a504-1df65d31a6d4.png)

Printed battery supports

**Comment by PedroMS3** [comment]
the supports for the pcb have to be redesigned and reprinted

**Comment by PedroMS3** [comment]
the supports have been sucessfully mounted!! thanks to francisco freitas they were printed
![image](https://github.com/AutoMecUA/AutoMec-AD/assets/94935535/57017407-e4b5-4c63-b82d-568c23733083)
