### ISSUE TITLE
Develop better support for encoder

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#181]
Develop and possibly design and produce a better support solution for the encoder to the motor

**Comment by Lara-Duarte** [comment]
![image](https://user-images.githubusercontent.com/116599747/223237576-024025c4-d037-4fab-960b-a23ba7f192b5.png)
![image](https://user-images.githubusercontent.com/116599747/223238663-5c395f35-abf4-40f7-864d-bb179516a1fc.png)
![image](https://user-images.githubusercontent.com/116599747/223238900-70d56479-7de8-473f-b712-4331637f4cde.png)

**Comment by manuelgitgomes** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/58152228/231001196-e498818d-4c39-4f5a-9109-01489569798d.png)

This piece is implemented with hot glue in the car
