### ISSUE TITLE
Build from scratch a CNN (Convolution Neural Network) multi output regression that accepts gray images as inputs, and returns both the steering angle and the velocity          

### ISSUE THREAD

**Issue by DanielCoelho112** [AutoMecUA/AutoMec-AD#23]

**Comment by DanielCoelho112** [comment]
Not so good results... 

https://streamable.com/30nlrl

The model with constant velocity is much better, and this one took almost 1h in training, however, it is interesting to watch the robot slow down and search for the best position. 

For the training, I used 2 laps, but I have to admit, controlling the steering angle and the velocity is not an easy task...

**Comment by manuelgitgomes** [comment]
Very interesting results, but with that training time, it does not seem that promising

**Comment by DanielCoelho112** [comment]
True, but I increased the frequency up to 25 Hz, (2.5x) and used 40 epochs (2x) so I can't tell you if this new CNN is slower than the other or not.

**Comment by manuelgitgomes** [comment]
Possibly not feasible, maybe use RNN or reinforcement learning/deep reinforcement learning,
