### ISSUE TITLE
gazebo car not working on branch 09_08

### ISSUE THREAD

**Issue by brunomonteiro98** [AutomecUA/AutoMec-AD#26]
The launch happens but with a series of errors and the robot does not drive.
The PC is getting the twist messages from ROS-MOBILE but nothing seems to happen

**Comment by brunomonteiro98** [comment]
ERROR] [1628617787.064949, 1.978000]: Failed to load left_rear_axle_ctrlr
Example error:


[ERROR] [1628617787.069860582, 1.984000000]: Could not load controller 'right_rear_axle_ctrlr' because controller type 'effort_controllers/JointVelocityController' does not exist.
[ERROR] [1628617787.069911297, 1.984000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types

**Comment by manuelgitgomes** [comment]
You need to install the dependencies first.
`sudo apt install ros-noetic-ros-controllers
sudo apt-get install ros-noetic-ackermann-msgs`

Be sure to checkout if you have the new ROS key. You can add it by using:
`curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -`

**Comment by inaciose** [comment]
This shoul me marked soved

**Comment by DanielCoelho112** [comment]
Dependencies problem that will be solved with the user's guide.
