### ISSUE TITLE
New Deep Learning Archictecture to overtake the imbalance dataset problem

### ISSUE THREAD

**Issue by DanielCoelho112** [AutoMecUA/AutoMec-AD#30]
![new_arch_DL](https://user-images.githubusercontent.com/73063947/128917288-65f9d564-71b8-40ad-9404-41abdea2a72b.png)

This new arch consists of 1 classifier and 2 regressors.  The gray image first enters the classifier neural network and the model predicts a class : Forward, Steer Left, or Steer Right. If Forward is activated, the steering angle is 0. If Steer Left is activated, the image enters the left regressor and the steering angle is calculated. The same goes for Steer Right. 

The Left Regressor has only been trained using images to turn left while the Right Regressor was trained only using images to turn right. This way, if we have an imbalanced dataset, there would not exist bias in the neural networks because there is no longer a mixture of all images.

**Comment by manuelgitgomes** [comment]
Done with under-sampling and data augmentation
