### ISSUE TITLE
Simulation word object meshes with no package dependencies 

### ISSUE THREAD

**Issue by inaciose** [AutomecUA/AutoMec-AD#45]
In the simulation world the objects with meshes have a dependency to pari_fnr.
Remove the dependency.

**Comment by manuelgitgomes** [comment]
Have they? Model1 and Model2? I believe Model3 does not have, because I helped a new member install the repo and it ran smoothly with Model3.

**Comment by inaciose** [comment]
The meshes of the objects used in gazebo, like the trafic cone you saw in our last meeting. Nothing to do with ML models.
I already solve the problem in branch dev_kinect.

**Comment by manuelgitgomes** [comment]
Nice!

**Comment by manuelgitgomes** [comment]
I will close this issue, solved with #49
