### ISSUE TITLE
gitignore prevent all jpgs to be uploaded

### ISSUE THREAD

**Issue by inaciose** [AutomecUA/AutoMec-AD#46]
# images
*.jpg

possible solutions:
- change the dataset storage folder to a folder outside the repo folder
- change the gitignore to only ignore jpg file above cnn/data folder

**Comment by inaciose** [comment]
error: The following untracked working tree files would be overwritten by merge:
	traxxas_description/meshes/kinect.jpg
Please move or remove them before you merge.
Aborting

**Comment by manuelgitgomes** [comment]
I believe the later solution you gave looks like the best. I will change that

**Comment by inaciose** [comment]
Closed by Pull Request 48
