### ISSUE TITLE
Signal recognition not working on gazebo

### ISSUE THREAD

**Issue by andrefdre** [AutomecUA/AutoMec-AD#57]
After running command `roslaunch simulation_bringup traxxas_drive_signal1.launch model:=modelX.h5` there was no option to change the signal panel. 
![image](https://user-images.githubusercontent.com/58526188/135172865-9ef73e83-0c93-4c15-9b5c-51cb7dee3e40.png)

**Comment by andrefdre** [comment]
This was done on the main branch

**Comment by inaciose** [comment]
@andrefdre you should run the following command in a new shell
roslaunch simulation_environment signal_panel.launch
Then you can change the signal on the panel
Please close this issue after verify the info above
