### ISSUE TITLE
3DP new camera structure

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#61]
The current wooden structure is neither precise nor aesthetically pleasing. A new one should be designed and 3DP.

**Comment by Ze6000** [comment]
The version 1 prototip is complete and now we will print in Fábrica da Ciencia Viva

**Comment by brunomonteiro98** [comment]
The step files were sent to Atena. Awating confirmation

**Comment by brunomonteiro98** [comment]
The inicial 2 parts were well printed. We need to print to 2 more.

**Comment by manuelgitgomes** [comment]
Mounted.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/58152228/160487172-3f978f90-b723-499a-87c4-e1174d068860.png)
