### ISSUE TITLE
Add instalation on other distros on user's guide to ros

### ISSUE THREAD

**Issue by brunomonteiro98** [AutoMecUA/AutoMec-AD#66]

**Comment by brunomonteiro98** [comment]
Source code install

**Comment by manuelgitgomes** [comment]
`sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'`

Possibly the error is in lsb_release, the user might solve it by changing it to focal.
