### ISSUE TITLE
Perform camera calibration on Kinect (physical)

### ISSUE THREAD

**Issue by DanielCoelho112** [AutoMecUA/AutoMec-AD#70]

**Comment by Almeida-a** [comment]
The camera intrinsic parameters seem to be correct.
Calibration will be carried out.

**Comment by manuelgitgomes** [comment]
> The camera intrinsic parameters seem to be correct. Calibration will be carried out.

You might have mistyped. The ROS parameters do not seem to be correct, so calibration is needed.

**Comment by manuelgitgomes** [comment]
This only makes sense after the hardware structure change.
