### ISSUE TITLE
Project and print 3DP support for PC

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#78]
As it currently is, PCs are very unstable when place on top of our robot, so there is a need for a support.

**Comment by brunomonteiro98** [comment]
@Ze6000  please put the stl files in teams to know what items to print

**Comment by brunomonteiro98** [comment]
The version of the gcode with the adhesion option doesn't work well, we need to do an updated version without that

**Comment by manuelgitgomes** [comment]
Print on my printer

**Comment by manuelgitgomes** [comment]
This needs to be done eventually, we should check out how Atlas does it.

**Comment by PedroMS3** [comment]
a prototype has been made, but after further analysis with the rest od the team, it was concluded that we should keep it simple, using some pieces of acrylic, sponge and bolts. Nonetheless, here are some some pictures of the prototype.
![Captura de Ecrã (202)](https://user-images.githubusercontent.com/94935535/178440359-0943c57f-4c70-46a0-bf0d-0cd3fb64abc1.png)
![Captura de Ecrã (203)](https://user-images.githubusercontent.com/94935535/178440366-832ddf72-ad76-46c4-8359-f3a78f2746ec.png)

**Comment by PedroMS3** [comment]
we came to the conclusion that it would be better to have a wider board, and also maybe a bit longer to better accomodate the pc

**Comment by PedroMS3** [comment]
i got the new mdf board and will bring it to aveiro this week, also i drew the new base in solidworks just have to double check some measures to make the final drawing
