### ISSUE TITLE
New wheel design

### ISSUE THREAD

**Issue by brunomonteiro98** [AutoMecUA/AutoMec-AD#90]
The new wheel design should be "full" and have a larger chamfer to increase the clearence.

**Comment by brunomonteiro98** [comment]
The new version has been design but it lacks the printing it self

**Comment by Almeida-a** [comment]
Reopened due to the bad design of the inner diameter of the wheel.

**Comment by brunomonteiro98** [comment]
1 unit of version9 was printed and is waiting physical tests, however due to the circular tolerance this part is best printed in Fabrica da Ciencia or Atena

**Comment by manuelgitgomes** [comment]
@brunomonteiro98 Comment on the state of this issue
