### ISSUE TITLE
Finish the track 

### ISSUE THREAD

**Issue by brunomonteiro98** [AutoMecUA/AutoMec-AD#92]
In fabrica de ciencia viva

**Comment by manuelgitgomes** [comment]
Schedule tommorrow.

**Comment by brunomonteiro98** [comment]
@Ze6000 buys the white tape

**Comment by manuelgitgomes** [comment]
It's now done

**Comment by manuelgitgomes** [comment]
Some pictures:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/58152228/141146965-63a2e3a6-172c-4c47-a834-76b47a912e52.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/58152228/141146971-1bda0c23-aacb-452c-a495-b2fcc12d32d0.png)
