### ISSUE TITLE
Shopping

### ISSUE THREAD

**Issue by brunomonteiro98** [AutoMecUA/AutoMec-AD#95]
We need to buy a new webcam, a powerbank and a powerbank charger

**Comment by manuelgitgomes** [comment]
BOM list here! https://teams.microsoft.com/l/file/E20D083D-F77D-4256-955A-32EE9DCCD833?tenantId=c1025aae-98b9-4021-b4b6-c201214b884e&fileType=xlsx&objectUrl=https%3A%2F%2Fuapt33090.sharepoint.com%2Fsites%2FOP_AutoMec_geral%2FShared%20Documents%2FReuni%C3%B5es%20Carro%2FHardware%20Geral%2FOr%C3%A7amentos%2Fcam-powerbank-carr.xlsx&baseUrl=https%3A%2F%2Fuapt33090.sharepoint.com%2Fsites%2FOP_AutoMec_geral&serviceName=teams&threadId=19:e7a9309831ad41ec8da850ec089f577f@thread.tacv2&groupId=47fff13a-cf3e-4b75-a443-7cfec9fcdc39

**Comment by manuelgitgomes** [comment]
Re-do with 10000 mah powerbank

**Comment by manuelgitgomes** [comment]
Updated!

**Comment by manuelgitgomes** [comment]
Asked financial department to proceed with the purchase. Closing the issue.
