### ISSUE TITLE
Investigate way to use CI

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#96]
Continuous Integration seems to be a nice step to take, in order to guarantee our code compiles and works on every machine

**Comment by Almeida-a** [comment]
Experimented using this [repo](https://github.com/ros-industrial/industrial_ci)'s ci in my fork, we can see in the [pull request section](https://github.com/Almeida-a/AutoMec-AD/pulls) as well as in this [branch](https://github.com/Almeida-a/AutoMec-AD/tree/junk/branch_ci_test) the tests that the github performs

**Comment by Almeida-a** [comment]
We have a template yml file for ci [here](https://github.com/Almeida-a/AutoMec-AD/blob/junk/branch_ci_test/.github/workflows/industrial_ci_action.yml), however changes may be made, so here is the related [documentation](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions) in order to learn how to make changes correctly.

**Comment by Almeida-a** [comment]
After some research upon this problem, I found this [post](https://answers.ros.org/question/320734/cannot-locate-rosdep-definition/) that indicates (in our case) that rosdep can't install the ackerman related libraries. Using some of these [customization variables](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#customize-within-the-ci-process) upon the industrial-ci process may solve this problem, namely some BEFORE_* variable (using them in the .yml file and setting to the appropriate value).

**Comment by Almeida-a** [comment]
It also seems that the default builder is catkin-tools. As indicated [here](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#optional-environment-variables), the BUILDER variable can change it to catkin-make. Should I change it?

**Comment by Almeida-a** [comment]
Setting up the variable BEFORE_INSTALL_DEPENDENCIES to install the missing ones "fixes" the problem. However, after it installs a load of packages, it holds without any response status. After 6h, it returns error (most likely of timing out).

Next steps:
- One more read of any useful information on the [documentation](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst);
- Try using a script to install all the dependencies needed to run AutoMec tools;
- Search for other ROS CI tools.

**Comment by manuelgitgomes** [comment]
The possible usage of CI does not warrant the time wasted in developing and refining the CI.
